<?xml version="1.0"?>
<package format="3">
  <name>warotrans_navigation</name>
  <version>0.1.0</version>
  <description>WaroTrans Nav2 configuration, maps, and behavior trees.</description>
  <maintainer email="dev@warotrans.local">WaroTrans Team</maintainer>
  <license>Proprietary</license>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>navigation2</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_behaviors</exec_depend>
  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>nav2_smoother</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
